name: Cleanup Preview on PR Close

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Sanitize branch name
        id: vars
        run: |
          slug="${{ github.head_ref }}" && slug="${slug//\//-}"
          echo "slug=$slug" >> $GITHUB_OUTPUT

      - name: Remove preview folder
        run: |
          rm -rf preview/${{ steps.vars.outputs.slug }}
          git rm -rf preview/${{ steps.vars.outputs.slug }} || echo "Folder not found, skipping"
          git commit -m "chore: cleanup preview for ${{ github.head_ref }}"
          git push
