name: Main CI

on:
  push:
    branches:
      - main

jobs:
  quality-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: packages/react
        run: npm ci

      - name: Run tests
        working-directory: packages/react
        run: npm run test

  quality-angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: packages/angular
        run: npm ci

      - name: Run tests
        working-directory: packages/angular
        run: echo "No tests for Angular package"
